url: https://zickkeen.github.io
baseurl: 
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

# Site settings
title: Zick keen
email: jackkinny@gmail.com
description: "Web Developer."


# Team names, titles and social links
people:
- name: Erzawansyah
  pic: 1
  position: Front-End Developer
  social:
    - title: github
      url: https://github.com/erzawansyah
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Front-End
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://www.twitter.com/zickkeen
  - title: facebook
    url: https://www.facebook.com/zickeen
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: https://bitbucket.org/zickkeen/
  - title: github
    url: http://github.com/zickkeen
  - title: instagram
    url: https://www.instagram.com/zickkeen

# Postal address (add as many lines as necessary)
address:
  - line: Jl. Pesantren 19
  - line: Wonosari, Malang, ID

# Build settings
markdown: kramdown
permalink: pretty